
# INSTALL PLUGINS 
# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions

# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

#  https://dh4ihowhowe4s.cloudfront.net

# Git stash untracked
function gitSU {
  git stash --keep-index -u
}

# Git revert one
function gitR {
  git reset --soft HEAD~1
}

function gitbr {
  git branch -r | grep -v HEAD | while read b; do git log --color --format="%ci _%C(magenta)%cr %C(bold cyan)$b%Creset %s %C(bold blue)<%an>%Creset" $b | head -n 1; done | sort -r | cut -d_ -f2- | sed 's;origin/;;g' | head -10
}

function gitbl {
  git show-branch --color --list | grep -v HEAD | while read b; do git log --color --format="%ci _%C(magenta)%cr %C(bold cyan)$b%Creset %s %C(bold blue)<%an>%Creset" $b | head -n 1; done | sort -r | cut -d_ -f2- | sed 's;origin/;;g' | head -10
}


#  KILL PORTS
function killPort {
  kill $(lsof -t -i:$1)
}


function getPluginsZsh {
  brew install zsh-completions
  brew install zsh-autosuggestions
  brew install zsh-syntax-highlighting
}

 plugins=(
      git 
      zsh-autosuggestions 
      zsh-syntax-highlighting
)




