#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

# Run JEST
npx jest -o --coverage --coverageReporters="json-summary" 

# Run Valdiation
node .husky/hook_validate.js

echo "Linting..."

# Find all modified .js files in the current directory
echo "Files changed:" + $(git diff --name-only  | grep '.js$' )

git diff --name-only  | grep '.js$' | xargs eslint --fix

echo "Linting complete."
